plugins:
    - promise
env:
    es6: true
    node: true
    mocha: true
extends:
    - eslint:recommended
    - plugin:promise/recommended
parserOptions:
    ecmaVersion: 8
    sourceType:
        - script
rules:
    indent:
        - error
        - 4
    quotes:
        - error
        - single
    semi:
        - error
        - always
    no-unused-vars:
        - error
        - args: none
    no-console: warn
    curly: error
    eqeqeq: error
    no-throw-literal: error
    strict: error
    no-var: error
    dot-notation: error
    no-tabs: error
    no-trailing-spaces: error
    no-use-before-define: error
    no-useless-call: error
    no-with: error
    operator-linebreak: error
    require-jsdoc:
        - error
        - require:
            ClassDeclaration: true
            MethodDefinition: true
            FunctionDeclaration: true
    valid-jsdoc:
        - error
        - requireReturn: false
    yoda: error
    promise/always-return: error
    promise/no-return-wrap: error
    promise/param-names: error
    promise/catch-or-return: error
    promise/no-native: off
    promise/no-nesting: warn
    promise/no-promise-in-callback: warn
    promise/avoid-new: off
    promise/no-new-statics: error
    promise/no-return-in-finally: warn
    promise/valid-params: warn
